// Andrew Brain local server.
// - Serves the Dashboard app at / and the wiki at /wiki/
// - Exposes a write API for capture/create/edit
// - Watches wiki/ with chokidar and rebuilds Dashboard/manifest.js on any change
// Run: node Dashboard/server.js (or `npm --prefix Dashboard start`)
// Binds to 127.0.0.1 only — do not expose to the network.

const http = require("http");
const fs = require("fs");
const fsp = fs.promises;
const path = require("path");
const crypto = require("crypto");
const chokidar = require("chokidar");

const PORT = Number(process.env.PORT) || 5180;
const HOST = "127.0.0.1";
const ROOT = path.resolve(__dirname, "..");
const WIKI = path.join(ROOT, "wiki");
const RAW = path.join(ROOT, "raw");
const DASHBOARD = __dirname;
const MANIFEST_FILE = path.join(DASHBOARD, "manifest.js");
const MAX_UPLOAD_BYTES = 25 * 1024 * 1024; // 25MB

const UPLOAD_EXTS = new Set([".pdf", ".docx", ".doc", ".md", ".txt", ".rtf", ".png", ".jpg", ".jpeg", ".webp", ".gif", ".csv", ".xlsx", ".xls", ".pptx", ".ppt", ".epub", ".html", ".htm", ".json"]);

function safeFilename(name) {
  // Strip directory parts, keep extension, allow alphanum + hyphen + underscore + dot.
  const base = path.basename(String(name || "upload"));
  const cleaned = base.replace(/[^A-Za-z0-9._-]/g, "-").replace(/-+/g, "-");
  return cleaned.length > 120 ? cleaned.slice(-120) : cleaned;
}

// ---- Manifest build (inlined + reused from build-manifest.js logic) --------

// Wiki root reserves three filenames for bookkeeping (index, log, overview).
// Everything else at the root — including captures — is a real page.
const WIKI_ROOT_BOOKKEEPING = new Set(["index.md", "log.md", "overview.md"]);

function listWikiMarkdown() {
  const out = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.isFile() && entry.name.endsWith(".md")) {
        out.push(path.relative(WIKI, full).replace(/\\/g, "/"));
      }
    }
  };
  walk(WIKI);
  return out
    .filter((f) => !(f.indexOf("/") === -1 && WIKI_ROOT_BOOKKEEPING.has(f)))
    .sort();
}

let manifestRebuildPending = false;
function rebuildManifest() {
  if (manifestRebuildPending) return;
  manifestRebuildPending = true;
  setTimeout(() => {
    manifestRebuildPending = false;
    try {
      const files = listWikiMarkdown();
      const content = `// Auto-generated by server.js. Do not edit by hand.\nwindow.AB_MANIFEST = ${JSON.stringify(files, null, 2)};\n`;
      fs.writeFileSync(MANIFEST_FILE, content);
      console.log(`[manifest] ${files.length} entries`);
    } catch (e) {
      console.error("[manifest] rebuild failed:", e.message);
    }
  }, 120); // debounce so a burst of writes produces a single rebuild
}

// ---- Static file serving ---------------------------------------------------

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js":   "application/javascript; charset=utf-8",
  ".jsx":  "application/javascript; charset=utf-8",
  ".css":  "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".md":   "text/markdown; charset=utf-8",
  ".png":  "image/png",
  ".jpg":  "image/jpeg",
  ".jpeg": "image/jpeg",
  ".svg":  "image/svg+xml",
  ".ico":  "image/x-icon",
  ".woff2": "font/woff2",
};

async function serveStatic(req, res) {
  // Resolve requested path against ROOT (project root — Dashboard/ and wiki/ both live under it)
  let urlPath = decodeURIComponent(req.url.split("?")[0]);
  // Default landing → /Dashboard/
  if (urlPath === "/" || urlPath === "") urlPath = "/Dashboard/";
  if (urlPath.endsWith("/")) urlPath += "index.html";

  const filePath = path.normalize(path.join(ROOT, urlPath));
  if (!filePath.startsWith(ROOT)) {
    res.writeHead(403); res.end("forbidden"); return;
  }
  try {
    const stat = await fsp.stat(filePath);
    if (stat.isDirectory()) {
      const indexFile = path.join(filePath, "index.html");
      const body = await fsp.readFile(indexFile);
      res.writeHead(200, { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" });
      res.end(body);
      return;
    }
    const ext = path.extname(filePath).toLowerCase();
    const body = await fsp.readFile(filePath);
    res.writeHead(200, { "content-type": MIME[ext] || "application/octet-stream", "cache-control": "no-store" });
    res.end(body);
  } catch (e) {
    res.writeHead(404, { "content-type": "text/plain" });
    res.end("not found: " + urlPath);
  }
}

// ---- API helpers -----------------------------------------------------------

function readJson(req) {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", (chunk) => {
      data += chunk;
      if (data.length > 1_000_000) {
        req.destroy();
        reject(new Error("payload too large"));
      }
    });
    req.on("end", () => {
      try { resolve(data ? JSON.parse(data) : {}); }
      catch (e) { reject(e); }
    });
    req.on("error", reject);
  });
}

function sendJson(res, status, body) {
  res.writeHead(status, { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" });
  res.end(JSON.stringify(body));
}

function slugify(text) {
  return String(text || "")
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 60);
}

function isValidSlug(s) { return /^[a-z0-9][a-z0-9-]{0,80}$/.test(s); }

const VALID_TYPES = new Set(["concept", "entity", "source", "analysis", "journal", "section", "course"]);
const TYPE_TO_FOLDER = {
  concept:  "concepts",
  entity:   "entities",
  source:   "sources",
  analysis: "analyses",
  journal:  "journal",
  section:  "sections",
  course:   "sections", // legacy alias
};

function escapeYamlScalar(v) {
  if (v == null) return '""';
  const s = String(v);
  if (/^[A-Za-z0-9_\-./ ]+$/.test(s) && !/^\s|\s$/.test(s)) return `"${s.replace(/"/g, '\\"')}"`;
  return JSON.stringify(s);
}

function frontmatterBlock(meta) {
  const lines = ["---"];
  if (meta.title != null)   lines.push(`title: ${escapeYamlScalar(meta.title)}`);
  if (meta.type  != null)   lines.push(`type: ${meta.type}`);
  if (meta.section != null) lines.push(`section: ${escapeYamlScalar(meta.section)}`);
  if (meta.created != null) lines.push(`created: ${meta.created}`);
  if (meta.updated != null) lines.push(`updated: ${meta.updated}`);
  if (Array.isArray(meta.tags) && meta.tags.length) {
    lines.push(`tags: [${meta.tags.map((t) => escapeYamlScalar(t)).join(", ")}]`);
  }
  if (Array.isArray(meta.sources) && meta.sources.length) {
    // Strip any existing [[...]] wrapping before re-wrapping to avoid double-bracketing on roundtrip.
    const clean = meta.sources.map((s) => String(s).replace(/^\[\[|\]\]$/g, "").trim()).filter(Boolean);
    lines.push(`sources: [${clean.map((s) => `"[[${s}]]"`).join(", ")}]`);
  }
  lines.push("---");
  return lines.join("\n");
}

// Super-small YAML frontmatter parser — mirrors loader.jsx.
// Returns { meta, body }.
function parseFrontmatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return { meta: {}, body: text };
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!kv) continue;
    let v = kv[2].trim();
    if (v.startsWith("[") && v.endsWith("]")) {
      const inner = v.slice(1, -1).trim();
      const parts = []; let buf = ""; let q = null;
      for (const ch of inner) {
        if (q) { if (ch === q) q = null; else buf += ch; }
        else if (ch === '"' || ch === "'") q = ch;
        else if (ch === ",") { parts.push(buf.trim()); buf = ""; }
        else buf += ch;
      }
      if (buf.trim()) parts.push(buf.trim());
      v = parts.map((p) => p.replace(/^["']|["']$/g, ""));
    } else if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1);
    }
    meta[kv[1]] = v;
  }
  return { meta, body: m[2] };
}

function findPageFile(slug) {
  if (!/^[a-z0-9][a-z0-9._-]{0,120}$/i.test(slug)) return null;
  // Captures live at the wiki root — check there first.
  const rootCandidate = path.join(WIKI, slug + ".md");
  if (fs.existsSync(rootCandidate) && !WIKI_ROOT_BOOKKEEPING.has(slug + ".md")) return rootCandidate;
  for (const folder of ["concepts", "entities", "sources", "analyses", "journal", "sections"]) {
    const candidate = path.join(WIKI, folder, slug + ".md");
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

// ---- API routes ------------------------------------------------------------

async function handleApi(req, res, url) {
  try {
    // POST /api/capture — drop raw text or URL into wiki/raw/
    if (req.method === "POST" && url.pathname === "/api/capture") {
      const body = await readJson(req);
      const text = String(body.text || "").trim();
      if (!text) return sendJson(res, 400, { error: "text is required" });
      const isUrl = /^(https?:\/\/|www\.)/i.test(text);
      const today = new Date();
      const iso = today.toISOString().slice(0, 10);
      const hhmm = today.toTimeString().slice(0, 5).replace(":", "");
      const hint = slugify(isUrl ? (text.match(/\/\/([^/]+)/)?.[1] || "link") : text.split(/\s+/).slice(0, 6).join(" ")) || "scratch";
      const filename = `${iso}-${hhmm}-${hint}.md`;
      const filepath = path.join(WIKI, filename);
      const fm = frontmatterBlock({
        title: isUrl ? `Capture · ${hint}` : (text.slice(0, 80) + (text.length > 80 ? "…" : "")),
        type: "source",
        created: iso,
        updated: iso,
        tags: ["capture", isUrl ? "link" : "scratch"],
      });
      const content = `${fm}\n\n${text}\n`;
      await fsp.writeFile(filepath, content, "utf8");
      rebuildManifest();
      return sendJson(res, 201, { ok: true, path: filename, slug: filename.replace(/\.md$/, "") });
    }

    // POST /api/pages — create a new typed wiki page
    //   body: { slug, type, title, section?, tags?, sources?, body? }
    if (req.method === "POST" && url.pathname === "/api/pages") {
      const body = await readJson(req);
      const type = String(body.type || "").toLowerCase();
      if (!VALID_TYPES.has(type)) return sendJson(res, 400, { error: "invalid type" });
      const slug = body.slug ? String(body.slug).toLowerCase() : slugify(body.title);
      if (!isValidSlug(slug)) return sendJson(res, 400, { error: "invalid slug" });
      const folder = TYPE_TO_FOLDER[type];
      const existing = findPageFile(slug);
      if (existing) return sendJson(res, 409, { error: "page already exists", path: path.relative(WIKI, existing).replace(/\\/g, "/") });
      const iso = new Date().toISOString().slice(0, 10);
      const dir = path.join(WIKI, folder);
      await fsp.mkdir(dir, { recursive: true });
      const fm = frontmatterBlock({
        title: body.title || slug,
        type,
        section: body.section,
        created: iso,
        updated: iso,
        tags: Array.isArray(body.tags) ? body.tags : [],
        sources: Array.isArray(body.sources) ? body.sources : [],
      });
      const content = `${fm}\n\n# ${body.title || slug}\n\n${body.body || ""}\n`;
      const filepath = path.join(dir, slug + ".md");
      await fsp.writeFile(filepath, content, "utf8");
      rebuildManifest();
      return sendJson(res, 201, { ok: true, slug, path: `${folder}/${slug}.md` });
    }

    // PATCH /api/pages/:slug — update body (and optionally title/tags)
    //   body: { body?, title?, tags?, section? }
    if (req.method === "PATCH" && url.pathname.startsWith("/api/pages/")) {
      const slug = url.pathname.slice("/api/pages/".length);
      const filepath = findPageFile(slug);
      if (!filepath) return sendJson(res, 404, { error: "not found" });
      const body = await readJson(req);
      const existing = await fsp.readFile(filepath, "utf8");
      const { meta, body: oldBody } = parseFrontmatter(existing);
      const merged = {
        title: body.title != null ? body.title : meta.title,
        type: meta.type,
        section: body.section != null ? body.section : meta.section,
        created: meta.created || new Date().toISOString().slice(0, 10),
        updated: new Date().toISOString().slice(0, 10),
        tags: Array.isArray(body.tags) ? body.tags : (Array.isArray(meta.tags) ? meta.tags : (meta.tags ? [meta.tags] : [])),
        sources: Array.isArray(body.sources) ? body.sources : (Array.isArray(meta.sources) ? meta.sources : (meta.sources ? [meta.sources] : [])),
      };
      const newBody = body.body != null ? body.body : oldBody;
      const content = `${frontmatterBlock(merged)}\n\n${String(newBody).replace(/^\s+|\s+$/g, "")}\n`;
      await fsp.writeFile(filepath, content, "utf8");
      rebuildManifest();
      return sendJson(res, 200, { ok: true, slug, path: path.relative(WIKI, filepath).replace(/\\/g, "/") });
    }

    // GET /api/pages/:slug — fetch raw markdown (used by edit mode)
    if (req.method === "GET" && url.pathname.startsWith("/api/pages/")) {
      const slug = url.pathname.slice("/api/pages/".length);
      const filepath = findPageFile(slug);
      if (!filepath) return sendJson(res, 404, { error: "not found" });
      const content = await fsp.readFile(filepath, "utf8");
      const { meta, body } = parseFrontmatter(content);
      return sendJson(res, 200, { slug, meta, body, path: path.relative(WIKI, filepath).replace(/\\/g, "/") });
    }

    // POST /api/upload?filename=... — binary body → raw/{safe-filename}
    // The wiki schema says raw/ is immutable source documents. Claude Code ingests them
    // into wiki/sources/{slug}.md later; raw/ files stay forever.
    if (req.method === "POST" && url.pathname === "/api/upload") {
      const rawName = url.searchParams.get("filename") || "upload.bin";
      const filename = safeFilename(rawName);
      const ext = path.extname(filename).toLowerCase();
      if (UPLOAD_EXTS.size && ext && !UPLOAD_EXTS.has(ext)) {
        return sendJson(res, 415, { error: `extension not allowed: ${ext}` });
      }
      await fsp.mkdir(RAW, { recursive: true });
      // If name collides, suffix with a short hash.
      let finalName = filename;
      let destPath = path.join(RAW, finalName);
      if (fs.existsSync(destPath)) {
        const stem = filename.replace(/\.[^.]+$/, "");
        const suffix = crypto.randomBytes(3).toString("hex");
        finalName = `${stem}-${suffix}${ext}`;
        destPath = path.join(RAW, finalName);
      }
      // Stream body to disk with a byte cap.
      const chunks = [];
      let bytes = 0;
      let capped = false;
      await new Promise((resolve, reject) => {
        req.on("data", (chunk) => {
          bytes += chunk.length;
          if (bytes > MAX_UPLOAD_BYTES) {
            capped = true;
            req.destroy();
          } else {
            chunks.push(chunk);
          }
        });
        req.on("end", resolve);
        req.on("error", reject);
      });
      if (capped) return sendJson(res, 413, { error: "file too large (25MB max)" });
      if (chunks.length === 0) return sendJson(res, 400, { error: "empty body" });
      await fsp.writeFile(destPath, Buffer.concat(chunks));
      return sendJson(res, 201, { ok: true, filename: finalName, path: `raw/${finalName}`, bytes });
    }

    // POST /api/manifest/rebuild — force rebuild
    if (req.method === "POST" && url.pathname === "/api/manifest/rebuild") {
      rebuildManifest();
      return sendJson(res, 202, { ok: true });
    }

    sendJson(res, 404, { error: "unknown endpoint" });
  } catch (e) {
    console.error("[api error]", e);
    sendJson(res, 500, { error: e.message });
  }
}

// ---- Server ---------------------------------------------------------------

const server = http.createServer((req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);
  if (url.pathname.startsWith("/api/")) return handleApi(req, res, url);
  if (req.method !== "GET" && req.method !== "HEAD") {
    res.writeHead(405); res.end("method not allowed"); return;
  }
  serveStatic(req, res);
});

server.listen(PORT, HOST, () => {
  console.log(`Andrew Brain server → http://${HOST}:${PORT}/Dashboard/`);
  rebuildManifest(); // initial build on boot
});

// Watch wiki/ for out-of-band edits (Obsidian, VSCode) and keep the manifest fresh.
chokidar
  .watch(WIKI, { ignoreInitial: true, ignored: /(^|[\/\\])\../ })
  .on("add",    () => rebuildManifest())
  .on("unlink", () => rebuildManifest())
  .on("change", () => rebuildManifest());
